version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: voucher-postgres
    environment:
      POSTGRES_DB: voucherdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - voucher_pgdata:/var/lib/postgresql/data

volumes:
  voucher_pgdata: