spring.application.name=be-promo-voucher
server.port=8080

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:voucherdb}
spring.datasource.username=${POSTGRES_USER:voucher_user}
spring.datasource.password=${POSTGRES_PASSWORD:voucher_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true